### ISSUE TITLE
NullPointerException in StreamingCrawler.handleCanceled.

### ISSUE THREAD

**Issue by platonai** [platonai/pulsarRPA#37]
Exception in thread "DefaultDispatcher-worker-7" java.lang.NullPointerException
        at ai.platon.pulsar.crawl.impl.StreamingCrawler.handleCanceled(StreamingCrawler.kt:649)
        at ai.platon.pulsar.crawl.impl.StreamingCrawler.handleRetry(StreamingCrawler.kt:541)
        at ai.platon.pulsar.crawl.impl.StreamingCrawler.runLoadTaskWithEventHandlers(StreamingCrawler.kt:462)
        at ai.platon.pulsar.crawl.impl.StreamingCrawler.access$runLoadTaskWithEventHandlers(StreamingCrawler.kt:68)
        at ai.platon.pulsar.crawl.impl.StreamingCrawler$runLoadTaskWithEventHandlers$1.invokeSuspend(StreamingCrawler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by platonai** [comment]
Fixed in 1.10.12-SNAPSHOT.
